### PR TITLE
Bugfix: in InfoCustom, empty memberNames crashes the game

### PR DESCRIPTION
**Pull request by LozenChen**
**{Player.toFrame():} will crashes the game**
as after identifying toFrame() as a helperMethod, memberNames become empty, and is never checked. Then calling memberNames.First() will crash the game

bugfix: memberNames empty exception
feat: Add GetAssembly() helperMethod
support Collider in FormatValue
rewrite FormatValue to make it more extensible

### CODE REVIEW

**Comment by DemoJameson** [comment]
can you rename GetAssembly() to GetModName()
you can determine if the type has the same assembly in Everest.modules and get the mod name
also update the readme.md

**Comment by LozenChen** [comment]
updated
a minor bug (not tested but should exist): for objects from Everest or some EverestModules automatically created by Everest (e.g. LuaModule), object.GetModName() will be celeste

**Comment by DemoJameson** [comment]
I think the get mod name feature fits better in the console info, so I moved it

**Comment by LozenChen** [comment]
wow i don't even know that feature exists, that's nice

**Pull request merged**
